sudo: required
services:
  - docker

before_install:
  - docker build -t tshih/dockerlearning -f ./client/Dockerfile.dev ./client

script:
  - docker run tshih/dockerlearning npm test -- --coverage

after_success:
  - docker build -t tshih/client_prod ./client
  - docker build -t tshih/nginx_prod ./nginx
  - docker build -t tshih/server_prod ./server
  - docker build -t tshih/worker_prod ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tshih/client_prod
  - docker push tshih/nginx_prod
  - docker push tshih/server_prod
  - docker push tshih/worker_prod