sudo: required
services:
  - docker

before_install:
  - docker build -t thomasshih/dockerlearning -f ./client/Dockerfile.dev ./client

script:
  - docker run thomasshih/dockerlearning npm test -- --coverage

after_success:
  - docker build -t thomasshih/client_prod ./client
  - docker build -t thomasshih/nginx_prod ./nginx
  - docker build -t thomasshih/server_prod ./server
  - docker build -t thomasshih/worker_prod ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thomasshih/client_PRO
  - docker push thomasshih/nginx_prod
  - docker push thomasshih/server_prod
  - docker push thomasshih/worker_prod