apiVersion: skaffold/v2beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: stephengrider/multi-client
      sync:
        manual:
          - src: '**/*.js'
            dest: '.'
          - src: '**/*.css'
            dest: '.'
          - src: "**/*.html"
            dest: "."
      docker:
        dockerfile: Dockerfile.dev
      context: client
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml